services:
  - type: web
    name: maisoncleo-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"

  - type: web
    name: maisoncleo-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"
      - path: /assets/*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*.js
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*.css
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
